// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using CoreGraphics;
using AppKit;
using ChuckNorris;
using OxyPlot;
using OxyPlot.Axes;
using OxyPlot.Series;
using OxyPlot.Xamarin.Mac;

namespace ChuckNorrisMac
{
	public partial class MainWindowController : NSWindowController
	{
		ChuckNorrisQuotes chuckNorrisQuotes;

		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

		[Export ("initWithCoder:")]
		public MainWindowController (NSCoder coder) : base (coder)
		{
		}

		public MainWindowController () : base ("MainWindow")
		{
		}
			
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();
			QuotesView.Layer.BackgroundColor = new CGColor(1, 1, 1);
			chuckNorrisQuotes = new ChuckNorrisQuotes ();
		}

		public override void WindowDidLoad ()
		{
			base.WindowDidLoad ();

			var size = GraphView.Frame.Size;
			var frame = new CGRect (0, 0, size.Width, size.Height);
			var plotView = new PlotView (frame);
			plotView.Model = getGraph();
			GraphView.AddSubview(plotView);

		}

		partial void nextQuoteClicked (NSObject sender){
			
			var quote = chuckNorrisQuotes.GetNextQuote();
			labelChuckSays.StringValue = quote;
		}

		private PlotModel getGraph(){

			var plotModel = new PlotModel {
				Title = "Chuck Norris Performance",
				Subtitle = "",
				PlotType = PlotType.Cartesian,
				Background = OxyColors.White,

			};

			plotModel.Series.Add (new FunctionSeries (Math.Log, -10, 10, 0.1) { Color = OxyColors.Green });

			var xAxis = new LinearAxis
			{
				Position = AxisPosition.Bottom,
				Title = "Years",
				MajorGridlineStyle = LineStyle.Solid,
				MinorGridlineStyle = LineStyle.None,
			};

			plotModel.Axes.Add(xAxis);

			var yAxis = new LinearAxis
			{
				Position = AxisPosition.Left,
				Title = "Kicks per Second",
				MajorGridlineStyle = LineStyle.Solid,
				MinorGridlineStyle = LineStyle.None,
			};

			plotModel.Axes.Add(yAxis);

			return plotModel;
		}
	}
}
