// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using CoreGraphics;
using AppKit;
using ChuckNorris;
using OxyPlot;
using OxyPlot.Axes;
using OxyPlot.Series;
using OxyPlot.Xamarin.Mac;

namespace ChuckNorrisMac
{
	public partial class MainWindowController : NSWindowController
	{
		ChuckNorrisQuotes chuckNorrisQuotes;

		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

		[Export ("initWithCoder:")]
		public MainWindowController (NSCoder coder) : base (coder)
		{
		}

		public MainWindowController () : base ("MainWindow")
		{
		}
			
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();
			tabView.Layer.BackgroundColor = new CoreGraphics.CGColor(1, 1, 1);
			chuckNorrisQuotes = new ChuckNorrisQuotes ();
		}

		public override void WindowDidLoad ()
		{
			base.WindowDidLoad ();

			var size = GraphTabView.Frame.Size;
			var frame = new CGRect (0, 0, size.Width-10, size.Height-10);
			var plotView = new PlotView (frame);
			var model = new PlotModel{ Title = "Set Point Value" };
			model.Axes.Add (new LinearAxis { Position = AxisPosition.Bottom });
			model.Axes.Add (new LinearAxis { Position = AxisPosition.Left });
			model.Series.Add (new FunctionSeries (Math.Sin, 0, 10, 200));
			plotView.Model = model;
			GraphTabView.AddSubview(plotView);

		}

		partial void nextQuoteClicked (Foundation.NSObject sender){
			
			var quote = chuckNorrisQuotes.GetNextQuote();
			labelChuckSays.StringValue = quote;
		}

	}
}
